### ISSUE TITLE
Bibliography - should be called  References

### ISSUE THREAD

**Issue by suegrimmond** [Urban-Meteorology-Reading/SUEWS-Docs#1]
Bibliography - should be called  References

**Comment by sunt05** [comment]
this has been fixed by adding `\addto\captionsenglish{\renewcommand{\bibname}{References}}` to `latex_elements:'preamble'`

**Comment by sunt05** [comment]
and the redundant `Reference` issue can be resolved by [the workaround here](https://github.com/sphinx-doc/sphinx/issues/4775).
