### ISSUE TITLE
PopDens descriptions

### ISSUE THREAD

**Issue by ljarvi** [Urban-Meteorology-Reading/SUEWS-Docs#14]
**Describe the Issue**
In PopDensDay and PopDensNight descriptions AnthropHeatMethod = 2 should be replaced with EmissionsMethod = 2. 
TrafficRate and BuildEnergyUse descriptions: Do not use in v2018a - set to -999

**Location**
SUEWS_SiteSelect.txt 

**Screenshots**

**Additional context**

**Comment by sunt05** [comment]
corrected.
