### ISSUE TITLE
AnthropogenicCode

### ISSUE THREAD

**Issue by ljarvi** [Urban-Meteorology-Reading/SUEWS-Docs#15]
**Describe the Issue**
AnthropogenicCode description should be changed to
Code for modelling anthropogenic heat flux. Provides the link to column 1 of SUEWS_AnthropogenicHeat.txt, which contains the model coefficients for estimation of the anthropogenic heat flux (used if EmissionsMethod = 1, 2, 3 in RunControl.nml ). Value of integer is arbitrary but must match code specified in column 1 of SUEWS_AnthropogenicHeat.txt.

**Location**
SUEWS_SiteSelect.

**Screenshots**

**Additional context**

**Comment by sunt05** [comment]
corrected.
