### ISSUE TITLE
PopDensWD and PopDensWE missing from Siteselect

### ISSUE THREAD

**Issue by ljarvi** [Urban-Meteorology-Reading/SUEWS-Docs#17]
**Describe the Issue**
PopDensWD and PopDensWE missing from Siteselect. Their descriptions should read:

Code for population density profile (weekdays)
Provides the link to column 1 of SUEWS_Profiles.txt. Look the codes Value of integer is arbitrary but must match code specified in column 1 of SUEWS_Profiles.txt. Used for CO2 flux calculation - not used in v2018a 

Code for population density profile (weekends)
Provides the link to column 1 of SUEWS_Profiles.txt. Look the codes Value of integer is arbitrary but must match code specified in column 1 of SUEWS_Profiles.txt. Used for CO2 flux calculation - not used in v2018a 

**Location**
SiteSelect

**Screenshots**

**Additional context**

**Comment by sunt05** [comment]
@ljarvi Thanks for reporting this.

However, these codes are not existing in the latest version of SUEWS: `PopDensDay` and `PopDensNight` are the two related options, which are the same as stated in the previous versions. We may modify these in the future developments but should we close it for now? as we may want to freeze the code for this release (i.e., v2018a).
