### ISSUE TITLE
Meanings of `SnowLimPatch` and `SnowLimRemove` are not clear.

### ISSUE THREAD

**Issue by sunt05** [Urban-Meteorology-Reading/SUEWS-Docs#19]
**Describe the Issue**
Meanings of `SnowLimPatch` and `SnowLimRemove` are not clear.

**Location**
https://suews-docs.readthedocs.io/en/latest/input_files/SUEWS_SiteInfo/Input_Options.html?highlight=SnowLimPatch#cmdoption-arg-snowlimpatch

**Comment by ljarvi** [comment]
I updated their descriptions.
