### ISSUE TITLE
units - missing subscripts

### ISSUE THREAD

**Issue by suegrimmond** [Urban-Meteorology-Reading/SUEWS-Docs#2]
http://suews-docs.readthedocs.io/en/2018a.alpha/input_files/SUEWS_SiteInfo/SUEWS_Snow.html

**Comment by suegrimmond** [comment]
superscripts
http://suews-docs.readthedocs.io/en/2018a.alpha/input_files/SUEWS_SiteInfo/SUEWS_Snow.html

**Comment by sunt05** [comment]
fixed in a recent update. https://github.com/sunt05/SUEWS-Docs/commit/73d5535ced22eb467eeac87ac2b3249bcbace0e5
