### ISSUE TITLE
SUEWS Simple links

### ISSUE THREAD

**Issue by megstretton** [Urban-Meteorology-Reading/SUEWS-Docs#22]
The links to SUEWS Simple in section 8 (First 2 paragraphs) go to a page that doesn't exist yet.

https://suews-docs.readthedocs.io/en/latest/suews_related_softwares.html

![suews](https://user-images.githubusercontent.com/39263347/41527397-f1683c4c-72de-11e8-9769-7d5c684cbe0c.PNG)

**Comment by sunt05** [comment]
fixed.
