### ISSUE TITLE
Anthropogenic Heat

### ISSUE THREAD

**Issue by megstretton** [Urban-Meteorology-Reading/SUEWS-Docs#23]
In the Input Options section of the SUEWS manual (Section 4.2.14) one of the variables- EnEF_v_Jkm has the incorrect file location in the comments table. It currently links to the SUEWS_SiteSelect.txt document, however should surely be the SUEWS_AnthropogenicHeat.txt file instead.

https://suews-docs.readthedocs.io/en/latest/input_files/SUEWS_SiteInfo/Input_Options.html

![enef_v_jkm](https://user-images.githubusercontent.com/39263347/41787378-23435df0-7640-11e8-81b2-a4a34e6bb7fd.PNG)

**Comment by sunt05** [comment]
fixed.
