### ISSUE TITLE
Soil moisture can be calculated by the model (Not available in this version.).

### ISSUE THREAD

**Issue by suegrimmond** [Urban-Meteorology-Reading/SUEWS-Docs#24]
**Describe the Issue**
Soil moisture can be calculated by the model (Not available in this version.).

**Location**
Section 2.5

**Screenshots**

**Additional context**
I think what is written is not what is intended as otherwise SUEWS QE would be wrong

**Comment by sunt05** [comment]
It is on in the code: I think this is an incorrect statement in the doc.

**Comment by sunt05** [comment]
just corrected: deleted `(Not available in this version.)`
