### ISSUE TITLE
3.3. Download the program and example data files

### ISSUE THREAD

**Issue by suegrimmond** [Urban-Meteorology-Reading/SUEWS-Docs#25]
**Describe the Issue**
3.3. Download the program and example data files

- I think the links etc in the section need to be updated to the new location 

**Location**
https://suews-docs.readthedocs.io/en/latest/prepare-to-run-the-model.html

**Screenshots**

**Additional context**

**Comment by sunt05** [comment]
They now point to [our GitHub page](https://urban-meteorology-reading.github.io/SUEWS) and 2018b links are added there.

**Comment by suegrimmond** [comment]
This is still linked to the wrong page
It is still linked to:
https://urban-meteorology-reading.github.io/SUEWS
