### ISSUE TITLE
11. Benchmark Report

### ISSUE THREAD

**Issue by suegrimmond** [Urban-Meteorology-Reading/SUEWS-Docs#26]
**Describe the Issue**
Need a list of what has not been benchmarked as well

- [ ] Has Leena ever provided the snow data set?

- [ ] Snow?

- [ ] Tair?

**Location**
https://suews-docs.readthedocs.io/en/latest/benchmark_report.html

**Screenshots**

**Additional context**

**Comment by sunt05** [comment]
> * [ ]  Has Leena ever provided the snow data set?

No.

> * [ ]  Snow?

No.

> * [ ]  Tair?

No.

**Comment by sunt05** [comment]
added description for variables used in this benchmark

**Comment by suegrimmond** [comment]
https://suews-docs.readthedocs.io/en/latest/benchmark_report.html

- need to update variables etc
