### ISSUE TITLE
Human activity not used in v2018a

### ISSUE THREAD

**Issue by suegrimmond** [Urban-Meteorology-Reading/SUEWS-Docs#32]
**Describe the Issue*
Why does it say this  --
Human activity not used in v2018a

**Location**
https://suews-docs.readthedocs.io/en/latest/input_files/SUEWS_SiteInfo/SUEWS_Profiles.html

**Comment by sunt05** [comment]
Deleted as it is already in and used by anthropogenic emission module. 
That was copied in when first creating this manual from the wiki ancestor.
