### ISSUE TITLE
Incorrect description of PrecipLimSnow

### ISSUE THREAD

**Issue by tvkokkonen** [Urban-Meteorology-Reading/SUEWS-Docs#37]
**Describe the Issue**
Description of PrecipLimSnow in SUEWS_snow.txt says at the moment "Limit for hourly snowfall when the ground is fully covered with snow [mm]"

It should say "Temperature limit when precipitation falls as snow [°C]
▪ Auer (1974) [38]", based on earlier version (v2017b)

**Location**
https://suews-docs.readthedocs.io/en/latest/input_files/SUEWS_SiteInfo/SUEWS_Snow.html#suews-snow-txt

**Comment by sunt05** [comment]
fixed by https://github.com/Urban-Meteorology-Reading/SUEWS-Docs/commit/310f7f4106efff85b364d417ed0666791ee32c8f
